[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
seeds = false
skip-lint = false

[programs]
[programs.localnet]
marketplace = "HYLnmvP84H2xnoVq1RSduzvdBVSibs3ZyxNfK6ak8VwL"
marketplace_transfer_controller = "Bi2dB1dvse6p9nEDSseRC2qgnWXWFHadFSTxTjc4f5EF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
test = "ts-mocha -p ./protocol/tsconfig.json -t 1000000 protocol/tests/**/*.test.ts"
marketplace = "ts-mocha -p ./protocol/tsconfig.json -t 1000000 protocol/tests/marketplace/**/*.test.ts"

[workspace]
members = [ "rust/track-r5/*" ]
types = "protocol/src/idl"